#!/usr/bin/env python
import sys
sys.path.append('../../..')
import common_functions as CF

VERSION = 'v3'
if missing := CF.missing_exe(["java", ]):
    print(f'Error:  missing required application {missing}')
    sys.exit(1)
args = CF.parse_args("Fake HDFView")
if args.version:
    print(f'OK {VERSION}')

